In [85]:
import cv2
import pandas as pd
import numpy as np

In [86]:
face_cascade=cv2.CascadeClassifier('./haarcascades/haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('./haarcascades/haarcascade_eye.xml')

In [87]:
def get_cropped_image_if_2_eyes(image_path):
    img = cv2.imread(image_path)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray,1.3,5)
    for (x,y,w,h) in faces:
        roi_gray = gray[y:y+h, x:x+w]
        roi_color = img[y:y+h, x:x+w]
        eyes = eye_cascade.detectMultiScale(roi_gray)
        if len(eyes)>=2:
            return roi_color

In [88]:
path_to_data='.raw images'
path_to_cr_data='.raw dataimages'

In [89]:
import os
import shutil
if os.path.exists(path_to_cr_data):
    shutil.rmtree(path_to_cr_data)
os.mkdir(path_to_cr_data)

In [90]:
count = 0
for entry in os.scandir(path_to_data):
    print(entry.path)
    count += 1
    roi_color = get_cropped_image_if_2_eyes(entry.path)
    if roi_color is not None:
        np_im=np.array(roi_color)
        print(np_im)

.raw images\10.jpg
[[[ 41  37  48]
  [ 49  45  56]
  [ 49  45  56]
  ...
  [ 19  18  22]
  [ 23  20  22]
  [ 23  20  22]]

 [[ 45  41  52]
  [ 53  49  60]
  [ 55  51  62]
  ...
  [ 21  20  24]
  [ 25  22  24]
  [ 24  21  23]]

 [[ 56  52  63]
  [ 63  59  70]
  [ 46  42  53]
  ...
  [ 21  20  24]
  [ 24  21  23]
  [ 24  22  22]]

 ...

 [[181 191 198]
  [181 191 198]
  [182 191 200]
  ...
  [ 79  91 115]
  [151 163 181]
  [165 176 190]]

 [[180 190 197]
  [180 190 197]
  [180 191 199]
  ...
  [ 84  96 120]
  [150 162 180]
  [164 175 189]]

 [[180 190 197]
  [180 189 198]
  [178 188 198]
  ...
  [ 91 102 129]
  [155 166 186]
  [168 179 193]]]
.raw images\1016.jpg
.raw images\1035.jpg
[[[62 66 84]
  [66 68 86]
  [57 57 75]
  ...
  [13 16 21]
  [11 14 18]
  [ 8 11 15]]

 [[60 62 80]
  [61 63 81]
  [51 51 69]
  ...
  [15 19 24]
  [12 15 19]
  [10 13 17]]

 [[46 48 66]
  [42 44 62]
  [37 36 56]
  ...
  [16 19 27]
  [10 14 19]
  [ 9 12 16]]

 ...

 [[12 13 34]
  [ 9 10 31]
  [ 9 10 30]
  ...


[[[ 46  55  64]
  [ 46  54  61]
  [ 30  34  39]
  ...
  [ 51  49  49]
  [ 56  52  51]
  [ 65  61  60]]

 [[ 45  54  63]
  [ 42  48  55]
  [ 32  36  41]
  ...
  [ 55  52  54]
  [ 52  50  50]
  [ 52  47  48]]

 [[ 45  52  61]
  [ 24  30  37]
  [ 33  36  41]
  ...
  [ 53  51  57]
  [ 54  51  53]
  [ 51  46  48]]

 ...

 [[165 170 185]
  [179 180 200]
  [195 193 215]
  ...
  [104 140 156]
  [ 61 103 116]
  [179 221 233]]

 [[205 209 228]
  [221 221 245]
  [146 143 169]
  ...
  [135 164 185]
  [ 93 127 143]
  [183 218 232]]

 [[219 221 245]
  [198 196 225]
  [163 158 189]
  ...
  [157 179 204]
  [135 162 183]
  [176 203 223]]]
.raw images\1190.jpg
[[[ 55  53  59]
  [ 54  50  56]
  [ 55  51  57]
  ...
  [ 27  20  25]
  [ 27  19  26]
  [ 27  20  27]]

 [[ 46  42  47]
  [ 42  38  43]
  [ 43  39  45]
  ...
  [ 28  21  26]
  [ 28  20  27]
  [ 28  20  27]]

 [[ 48  44  49]
  [ 42  38  43]
  [ 44  40  46]
  ...
  [ 29  19  25]
  [ 28  20  27]
  [ 29  21  28]]

 ...

 [[233 227 238]
  [229 223 234]

[[[ 14  16  17]
  [ 23  22  26]
  [ 21  20  24]
  ...
  [  6   5   7]
  [  8   7   9]
  [ 17  16  18]]

 [[ 15  17  18]
  [ 24  25  29]
  [ 26  26  32]
  ...
  [  6   5   7]
  [ 10   9  11]
  [ 17  16  18]]

 [[ 16  17  21]
  [ 25  25  31]
  [ 34  34  40]
  ...
  [  6   5   7]
  [ 11  10  12]
  [ 13  12  14]]

 ...

 [[251 253 253]
  [253 252 254]
  [252 254 255]
  ...
  [ 32  42  60]
  [ 38  48  66]
  [ 60  68  85]]

 [[250 255 254]
  [251 253 254]
  [250 254 255]
  ...
  [ 30  39  59]
  [ 39  46  65]
  [ 51  59  76]]

 [[250 255 254]
  [249 253 254]
  [249 253 254]
  ...
  [ 29  38  58]
  [ 41  48  68]
  [ 36  44  61]]]
.raw images\1390.jpg
[[[ 43  66  58]
  [ 51  78  68]
  [ 63  92  77]
  ...
  [ 24  40  39]
  [ 29  44  36]
  [ 28  42  30]]

 [[ 47  70  62]
  [ 52  77  67]
  [ 66  95  80]
  ...
  [ 36  54  55]
  [ 41  57  50]
  [ 47  63  52]]

 [[ 48  72  62]
  [ 57  82  72]
  [ 67  95  82]
  ...
  [ 38  58  63]
  [ 51  70  67]
  [ 38  55  46]]

 ...

 [[ 87 108 123]
  [ 81  96 112]

.raw images\1537.jpg
[[[ 38  31  82]
  [ 43  35  82]
  [ 39  29  75]
  ...
  [  5  29  27]
  [ 17  42  38]
  [ 27  54  45]]

 [[ 30  24  71]
  [ 23  19  61]
  [ 28  20  61]
  ...
  [  8  32  30]
  [ 20  42  40]
  [ 25  51  45]]

 [[ 37  36  76]
  [ 33  29  70]
  [ 40  35  74]
  ...
  [ 10  34  34]
  [ 21  43  41]
  [ 23  49  43]]

 ...

 [[196 197 195]
  [198 199 197]
  [198 200 201]
  ...
  [162 173 170]
  [160 169 166]
  [156 162 161]]

 [[196 197 195]
  [198 199 197]
  [198 200 201]
  ...
  [160 171 169]
  [157 165 164]
  [154 161 158]]

 [[196 194 193]
  [197 195 195]
  [198 197 199]
  ...
  [152 162 162]
  [147 158 156]
  [148 155 152]]]
.raw images\1541.jpg
.raw images\1545.jpg
.raw images\1547.jpg
[[[ 30  54  44]
  [ 29  51  39]
  [ 27  49  37]
  ...
  [ 36  29  90]
  [ 24  13  81]
  [ 56  46 116]]

 [[ 35  56  47]
  [ 33  52  43]
  [ 29  48  39]
  ...
  [ 17  14  60]
  [ 47  38  95]
  [ 41  29  95]]

 [[ 36  55  46]
  [ 31  47  40]
  [ 27  41  35]
  ...
  [  5   7  42]
  [ 26  

[[[ 28  31  36]
  [ 65  68  73]
  [ 36  38  46]
  ...
  [191 182 215]
  [190 181 214]
  [190 182 213]]

 [[ 39  42  46]
  [ 45  48  53]
  [ 63  65  73]
  ...
  [192 183 216]
  [189 180 213]
  [189 180 213]]

 [[ 77  80  84]
  [ 31  34  38]
  [ 72  74  82]
  ...
  [191 182 215]
  [190 181 214]
  [190 181 214]]

 ...

 [[ 37  36  45]
  [ 40  39  48]
  [ 51  50  59]
  ...
  [ 49  45  64]
  [ 62  57  78]
  [ 63  59  84]]

 [[ 26  25  34]
  [ 30  29  38]
  [ 38  37  46]
  ...
  [ 50  47  63]
  [ 56  52  71]
  [ 62  60  80]]

 [[ 28  27  36]
  [ 46  45  54]
  [ 34  33  42]
  ...
  [ 47  44  59]
  [ 54  51  67]
  [ 66  64  83]]]
.raw images\1740.jpg
.raw images\175.jpg
.raw images\1758.jpg
[[[15 10  9]
  [14  9 10]
  [13  8 10]
  ...
  [ 7  6 10]
  [10  9 11]
  [11 10 12]]

 [[18 13 12]
  [12  7  8]
  [ 9  5 10]
  ...
  [ 5  4  8]
  [10  7  9]
  [10  9 11]]

 [[15 11 10]
  [ 9  6  8]
  [ 4  2  8]
  ...
  [ 3  1  7]
  [12  9 11]
  [ 9  6  8]]

 ...

 [[ 6  9  7]
  [ 7 10  8]
  [11 12  8]
  ...

.raw images\299.jpg
[[[ 12  17  32]
  [ 20  27  46]
  [ 14  26  50]
  ...
  [ 64  75  97]
  [ 66  80  98]
  [ 42  59  72]]

 [[ 16  22  41]
  [ 24  32  55]
  [ 14  25  55]
  ...
  [ 69  79 103]
  [ 71  82 102]
  [ 54  71  84]]

 [[ 18  24  47]
  [ 21  32  59]
  [ 16  31  64]
  ...
  [ 78  88 112]
  [ 62  76  95]
  [ 67  83  99]]

 ...

 [[  0   0  12]
  [  0   6  28]
  [ 21  38  71]
  ...
  [ 15  15  21]
  [  5   7   8]
  [  7  11  12]]

 [[  0   0   8]
  [  0   0  13]
  [  5  18  44]
  ...
  [ 17  19  27]
  [  1   4   8]
  [  5   8  12]]

 [[  1   3   4]
  [  0   0   6]
  [  0   3  20]
  ...
  [ 18  23  32]
  [  4   7  15]
  [  2   7  10]]]
.raw images\308.jpg
.raw images\319.jpg
[[[11  9  8]
  [ 8  6  5]
  [ 8  7  3]
  ...
  [10 10 10]
  [10  9 11]
  [ 9  9  9]]

 [[ 9 10  8]
  [ 6  7  5]
  [ 8  9  5]
  ...
  [ 9 12 10]
  [11 11 11]
  [10 10 10]]

 [[ 9 10  8]
  [ 6  7  5]
  [ 9 10  6]
  ...
  [10 12 12]
  [11 10 12]
  [11 11 11]]

 ...

 [[33 30 32]
  [31 30 32]
  [26 26 26]
  ...
 

  [107 131 137]]]
.raw images\389.jpg
.raw images\396.jpg
[[[ 30  29  55]
  [ 34  34  64]
  [ 50  51  85]
  ...
  [ 19  16   8]
  [ 16   8   1]
  [ 23  11   5]]

 [[ 35  36  64]
  [ 45  47  78]
  [ 61  63  98]
  ...
  [ 22  19  11]
  [ 29  19  12]
  [ 42  28  22]]

 [[ 50  52  82]
  [ 50  52  86]
  [ 43  49  84]
  ...
  [ 26  20  13]
  [ 41  31  24]
  [ 34  15  10]]

 ...

 [[ 74 103 170]
  [ 70  97 164]
  [ 65  92 159]
  ...
  [ 23  19   8]
  [ 23  19   8]
  [ 22  17   8]]

 [[ 79 108 175]
  [ 77 106 173]
  [ 76 103 170]
  ...
  [ 23  19   8]
  [ 23  19   8]
  [ 24  19  10]]

 [[ 79 108 177]
  [ 76 105 174]
  [ 74 103 170]
  ...
  [ 21  19   8]
  [ 21  19   8]
  [ 23  19   8]]]
.raw images\398.jpg
[[[ 32  28  33]
  [ 30  26  31]
  [ 25  22  24]
  ...
  [ 61  75 128]
  [ 55  68 114]
  [ 58  66 106]]

 [[ 39  35  41]
  [ 28  22  27]
  [ 24  18  23]
  ...
  [ 64  79 135]
  [ 58  72 120]
  [ 59  68 111]]

 [[ 42  35  42]
  [ 25  18  25]
  [ 20  14  19]
  ...
  [ 67  84 140]
  [ 58  73 122

.raw images\59.jpg
[[[ 12  17  32]
  [ 20  27  46]
  [ 14  26  50]
  ...
  [ 64  75  97]
  [ 66  80  98]
  [ 42  59  72]]

 [[ 16  22  41]
  [ 24  32  55]
  [ 14  25  55]
  ...
  [ 69  79 103]
  [ 71  82 102]
  [ 54  71  84]]

 [[ 18  24  47]
  [ 21  32  59]
  [ 16  31  64]
  ...
  [ 78  88 112]
  [ 62  76  95]
  [ 67  83  99]]

 ...

 [[  0   0  12]
  [  0   6  28]
  [ 21  38  71]
  ...
  [ 15  15  21]
  [  5   7   8]
  [  7  11  12]]

 [[  0   0   8]
  [  0   0  13]
  [  5  18  44]
  ...
  [ 17  19  27]
  [  1   4   8]
  [  5   8  12]]

 [[  1   3   4]
  [  0   0   6]
  [  0   3  20]
  ...
  [ 18  23  32]
  [  4   7  15]
  [  2   7  10]]]
.raw images\599.jpg
[[[ 94  83  39]
  [ 22  14   0]
  [  8   8   0]
  ...
  [  5   6  10]
  [  0   1   2]
  [  0   2   3]]

 [[ 87  76  32]
  [ 15   6   0]
  [ 12  10   0]
  ...
  [ 14  17  22]
  [  2   5   9]
  [  0   0   5]]

 [[ 78  65  21]
  [ 13   4   0]
  [ 19  17   7]
  ...
  [ 22  28  35]
  [  9  13  18]
  [  0   1   9]]

 ...

 [[159 146   

[[[ 11  17  24]
  [ 13  16  24]
  [ 12  15  23]
  ...
  [ 61  82 103]
  [ 60  82 100]
  [ 58  78  96]]

 [[ 10  16  23]
  [ 12  15  23]
  [ 12  15  23]
  ...
  [ 63  84 105]
  [ 65  87 105]
  [ 64  84 102]]

 [[  9  15  22]
  [ 11  14  22]
  [ 12  15  23]
  ...
  [ 64  85 106]
  [ 70  92 110]
  [ 72  92 110]]

 ...

 [[ 10  15  24]
  [  5  10  19]
  [  8  13  22]
  ...
  [  6   2   1]
  [  6   2   1]
  [  3   2   0]]

 [[  8  13  22]
  [  5  10  19]
  [  8  13  22]
  ...
  [  7   3   2]
  [  5   2   0]
  [  3   2   0]]

 [[  8  13  22]
  [  5  10  19]
  [  9  14  23]
  ...
  [  8   3   2]
  [  4   1   0]
  [  3   2   0]]]
.raw images\826.jpg
.raw images\828.jpg
[[[ 37  47  54]
  [ 35  45  52]
  [ 34  44  51]
  ...
  [ 27  40  42]
  [ 28  41  43]
  [ 28  40  44]]

 [[ 40  50  57]
  [ 39  49  56]
  [ 41  51  58]
  ...
  [ 29  41  45]
  [ 29  41  45]
  [ 28  40  44]]

 [[ 40  50  57]
  [ 41  51  58]
  [ 41  51  58]
  ...
  [ 29  41  45]
  [ 29  41  45]
  [ 29  41  45]]

 ...

 [[ 33  39  

In [91]:
#from numpy import savetxt
#savetxt("data1.csv", np_im.reshape((3,-1)), fmt="%s", header=str(np_im.shape))
DF = pd.DataFrame(np_im.reshape(3,-1))
  
# save the dataframe as a csv file
DF.to_csv("data4.csv")

In [92]:
df=pd.read_csv("data4.csv")
df

Unnamed: 0    0   1    2    3   4   5    6   7   8  ...  7215  7216  7217  \
0           0   26  37   57   29  32  46   46  42  53  ...    27    31    56   
1           1   33  53   16   28  52  11   27  56  16  ...   134   219   115   
2           2  211  86  122  216  32  70  166  34  76  ...   152   178   160   

   7218  7219  7220  7221  7222  7223  7224  
0    32    36    55    28    34    53    26  
1   147   236   105   139   229    84   118  
2   161   141   124   121   166   150   143  

[3 rows x 7226 columns]

In [93]:
df.isnull().sum()

Unnamed: 0    0
0             0
1             0
2             0
3             0
             ..
7220          0
7221          0
7222          0
7223          0
7224          0
Length: 7226, dtype: int64

In [94]:
df=pd.get_dummies(df,drop_first=True)

In [95]:
df

Unnamed: 0    0   1    2    3   4   5    6   7   8  ...  7215  7216  7217  \
0           0   26  37   57   29  32  46   46  42  53  ...    27    31    56   
1           1   33  53   16   28  52  11   27  56  16  ...   134   219   115   
2           2  211  86  122  216  32  70  166  34  76  ...   152   178   160   

   7218  7219  7220  7221  7222  7223  7224  
0    32    36    55    28    34    53    26  
1   147   236   105   139   229    84   118  
2   161   141   124   121   166   150   143  

[3 rows x 7226 columns]

In [96]:
df.fillna(df.mean())

Unnamed: 0    0   1    2    3   4   5    6   7   8  ...  7215  7216  7217  \
0           0   26  37   57   29  32  46   46  42  53  ...    27    31    56   
1           1   33  53   16   28  52  11   27  56  16  ...   134   219   115   
2           2  211  86  122  216  32  70  166  34  76  ...   152   178   160   

   7218  7219  7220  7221  7222  7223  7224  
0    32    36    55    28    34    53    26  
1   147   236   105   139   229    84   118  
2   161   141   124   121   166   150   143  

[3 rows x 7226 columns]

In [97]:
df.dropna(inplace=True)


In [98]:
#df.drop('cluimg',axis=1,inplace=True)
#df.drop(['C', 'D'], axis = 1)

In [99]:
df

Unnamed: 0    0   1    2    3   4   5    6   7   8  ...  7215  7216  7217  \
0           0   26  37   57   29  32  46   46  42  53  ...    27    31    56   
1           1   33  53   16   28  52  11   27  56  16  ...   134   219   115   
2           2  211  86  122  216  32  70  166  34  76  ...   152   178   160   

   7218  7219  7220  7221  7222  7223  7224  
0    32    36    55    28    34    53    26  
1   147   236   105   139   229    84   118  
2   161   141   124   121   166   150   143  

[3 rows x 7226 columns]

In [100]:
df.shape

(3, 7226)

In [101]:
x=df.iloc[:,:7224]
x=x.astype('int')
y=df.iloc[:,7224]
y=y.astype('int')

In [102]:
from sklearn.model_selection import train_test_split


In [103]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [104]:
from sklearn.cluster import KMeans
km=KMeans(n_clusters=2)

In [105]:
y_pred=km.fit_predict(df)

In [106]:
y_pred

array([0, 0, 1])

In [115]:
image_path1="fru.jpg"

In [116]:
img1 = cv2.imread(image_path1)
gray1 = cv2.cvtColor(img1,cv2.COLOR_BGR2GRAY)
faces1 = face_cascade.detectMultiScale(gray1,1.3,5)
#print(len(faces1))
for (x1,y1,w1,h1) in faces1:
    roi_gray1 = gray1[y1:y1+h1, x1:x1+w1]
    roi_color1 = img1[y1:y1+h1, x1:x1+w1]
    eyes1 = eye_cascade.detectMultiScale(roi_gray1)
    #print(len(eyes1))
    if len(eyes1)>=1:
        i=np.array(roi_gray1).reshape(2,-1)
        p=km.fit_predict(i)
        #print(p)
        if p[0]==1:
            print("indian human")
        if p[0]==0:
            print("not a indian")
if len(faces1)==0:
        print("not a human")

not a human
